[project]
name = "turtles"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "trdesilva", email = "thomas.r.desilva@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.5.2",
    "parse>=1.22.1",
]

[project.scripts]
turtles = "turtles:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
