[project]
name = "rbe550"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "trdesilva", email = "5818730+trdesilva@users.noreply.github.com" }
]
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.24.4",
]

[project.scripts]
rbe550 = "rbe550:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
