[project]
name = "flatland"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "trdesilva", email = "5818730+trdesilva@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.5.3",
    "turtles",
]

[project.scripts]
flatland = "flatland:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
turtles = { path = "../turtles", editable = true }
